require("dotenv").config()
const app = require("./src/app")
const connectToDB = require("./src/config/database")
const invokeGeminiAi = require("./src/services/ai.service")
const getInterviewData = require("./src/services/temp")
const generateInterviewReport = require("./src/services/ai.service")
require("./src/config/passport")
connectToDB()
// invokeGeminiAi()
 const prompt = getInterviewData()
// console.log(prompt)
// generateInterviewReport(prompt)

app.listen(3000,()=>{
    console.log("Server is running on port 3000")
})